[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools >= 61.2.0",
  "setuptools-scm >= 6.3.2",
  "wheel >= 0.37.0",
]

[project]
name = "demo"
description = "Demo repository for tutorials"
readme = "README.md"
license = {file = "LICENSE.md"}
requires-python = ">=3.9"
dynamic = [
  "version",
]
dependencies = [
  "astropy >= 5.0.1",
  "numpy >= 1.21.0",
  "plasmapy >= 2023.5.1",
]
[project.optional-dependencies]
docs = [
  "docutils >= 0.18.1",
  "jinja2 >= 3.1.2",
  "nbsphinx >= 0.9.1",
  "numpydoc >= 1.5.0",
  "pillow >= 9.5.0",
  "pygments >= 2.15.0",
  "sphinx >= 6.1.3",
  "sphinx-changelog >= 1.3.0",
  "sphinx_rtd_theme >= 1.2.0",
  "towncrier >= 22.12",
  "tox >= 4.4.0",
]
tests = [
  "pre-commit >= 3.0.0",
  "tomli >= 2.0.1",
  "tox >= 4.3.1",
]

[tool.setuptools.packages.find]
exclude = ["docs/automodapi", "demo/_dev"]
namespaces = false

[tool.setuptools_scm]
write_to = "demo/_version.py"

[tool.isort]
line_length = 88
wrap_length = 80
sections = ["FUTURE", "STDLIB", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["demo", ]
default_section = "STDLIB"
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_alphabetical_sort_within_sections = true
honor_noqa = true
lines_between_types = 1

[tool.pytest.ini_options]
minversion = "7.0.1"
testpaths = ['demo']
norecursedirs = ['build', 'docs', 'demo[\/]_dev']
doctest_optionflags = """
NORMALIZE_WHITESPACE
ELLIPSIS
NUMBER"""
addopts = "--doctest-modules --doctest-continue-on-failure"
filterwarnings = ["ignore:.*Creating", "a"]

[tool.coverage.report]
exclude_lines = [
  "coverage: ignore",
  "ImportError",
  "ModuleNotFoundError",
  "@vectorize",
  "@numba.vectorize",
  "@numba.jit",
  "@jit",
  "@numba.njit",
  "@njit",
  "@abstractmethod",
]

[tool.coverage.run]
omit = [
  "ci-helpers/*",
  "*/tests/*",
  "demo/utils/calculator/*",
  "demo/version.py",
  "demo/_dev/*",
]

[tool.build_docs]
source-dir = "docs"
build-dir = "docs/_build"
all_files = "1"

[tool.codespell]
skip = "*.png,*cache*,*egg*,.git,.hypothesis,.idea,.tox,_build,*charged_particle*.ipynb,venv"

[tool.gilesbot]

[tool.gilesbot.pull_requests]
enabled = true

[tool.gilesbot.towncrier_changelog]
enabled = true
changelog_skip_label = "No changelog entry needed"
changelog_missing = "Missing changelog entry (see `changelog/README.rst`)"
changelog_missing_long = "This pull request needs a changelog entry at `changelog/NUMBER.TYPE.rst`, where `NUMBER` is the pull request number and `TYPE` is one of `feature`, `trivial`, `doc`, `bugfix`, `breaking`, or `removal`.\n\nFor details, see: https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html#adding-a-changelog-entry"
verify_pr_number = true
number_incorrect = "Changelog entry number ≠ PR number (see `changelog/README.rst`)"
number_incorrect_long = "The changelog entry number does not match this pull request's number.\n\nWhen purposefully editing the changelog entry for a different pull request, set the 'No changelog entry needed' label to ignore this check."
type_incorrect = "Incorrect changelog type (see `changelog/README.rst`)"
type_incorrect_long = "The filename of the changelog entry must be of the form `changelog/NUMBER.TYPE.rst` where `TYPE` is one of `feature`, `trivial`, `doc`, `bugfix`, `breaking`, or `removal`.\n\nFor details, see: https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html#adding-a-changelog-entry"

[tool.ruff]
target-version = "py39"
extend-select = [
  "A", # flake8-builtins
  "ARG", # flake8-unused-arguments
  "B", # flake8-bugbear
  "BLE", # flake8-blind-except
  "C4", # flake8-comprehensions
  "C90", # mccabe
  "COM818", # trailing-comma-on-bare-tuple
  "D", # pydocstyle
  "FA", # flake8-future-annotations
  "FBT003", # flake8-boolean-trap
  "FLY", # flynt
  "ICN", # flake8-import-conventions
  "INP", # flake8-no-pep420
  "INT", # flake8-gettext
  "ISC", # flake8-implicit-str-concat
  "N", # pep8-naming
  "NPY", # numpy-deprecated-type-alias
  "PD", # pandas-vet
  "PGH", # pygrep-hooks
  "PIE", # flake8-pie
  "PLC", # pylint convention
  "PLE", # pylint errors
  "PLR", # pylint refactorings
  "PLW", # pylint warnings
  "PT", # flake8-pytest-style
  "PTH", # flake8-use-pathlib
  "PYI", # flake8-pyi
  "RUF005", # collection-literal-concatenation
  "RUF006", # asyncio-dangling-task
  "RUF007", # pairwise-over-zipped
  "RUF008", # mutable-dataclass-default
  "RUF009", # function-call-in-dataclass-default-argument
  "RUF010", # explicit-f-string-type-conversion
  "S", # flake8-bandit
  "SIM", # flake8-simplify
  "TID", # flake8-tidy-imports
  "TRY", # tryceratops
  "UP", # pyupgrade
  "W", # pycodestyle warnings
]
ignore = [
  "B028", # no-explicit-stacklevel
  "D105", # undocumented-magic-method (enable later?)
  "D200", # fits-on-one-line (incompatible with multiline short summaries)
  "D202", # no-blank-line-after-function
  "D205", # blank-line-after-summary (incompatible with multiline short summaries)
  "D401", # non-imperative-mood (enable later?)
  "E501", # line-too-long
  "N801", # invalid-class-name
  "N802", # invalid-function-name
  "N803", # invalid-argument-name
  "N806", # non-lowercase-variable-in-function
  "N816", # mixed-case-variable-in-global-scope
  "PLE0605", # invalid-all-format (flags `__all__ += __lite_funcs`, etc.)
  "PLR0913", # too-many-arguments
  "PLR2004", # magic-value-comparison
  "PT007", # pytest-parametrize-values-wrong-type
  "PT011", # pytest-raises-too-broad
  "PT012", # pytest-raises-multiple-statements (enable later?)
  "PT019", # pytest-fixture-param-without-value (enable later?)
  "S101", # asserts
  "SIM117", # multiple-with-statements (remove for Python 3.10+)
  "SIM300", # yoda-conditions
  "TRY003", # raise-vanilla-args
  "TRY301", # raise-within-try
  "UP006", # non-pep585-annotation
  "UP007", # non-pep604-annotation
  "UP025", # unicode-kind-prefix
]
extend-exclude = [
  ".jupyter",
  "__pycache__",
  "_build",
  "_dev",
]
dummy-variable-rgx = "Z|mass_numb|request|event"
namespace-packages = [".github/workflows", "docs"]
show-fixes = true
show-source = true

[tool.ruff.flake8-import-conventions.aliases]
"astropy.units" = "u"
"matplotlib.pyplot" = "plt"
numpy = "np"
pandas = "pd"

[tool.ruff.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.mccabe]
max-complexity = 50

[tool.ruff.per-file-ignores]
"__init__.py" = ["D104", "E402", "F401", "F402", "F403"] # ignore import errors
".github/scripts/*.py" = ["D103", "INP001"]
"docs/conf.py" = ["D100", "D103", "E402"]
"setup.py" = ["D100"]
"test_*" = ["D100", "D101", "D102", "D103", "D104", "D209", "D400", "D401"]
"*/*/tests/__init__.py" = ["D104"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.towncrier]
package = "demo"
name = "demo"
filename = "CHANGELOG.rst"
directory = "changelog/"
title_format = "{name} v{version} ({project_date})"
issue_format = ":pr:`{issue}`" # Despite the name mismatch, we use this for linking to PRs
wrap = true

[[tool.towncrier.type]]
directory = "breaking"
name = "Backwards Incompatible Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "trivial"
name = "Trivial/Internal Changes"
showcontent = true
